Addresse:
    type: entity
    table: addresse
    indexes:
        client_const:
            columns:
                - client_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rue:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        zipcode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        client:
            targetEntity: Client
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
