Produit:
    type: entity
    table: produit
    indexes:
        categorie_const:
            columns:
                - categorie_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: false
        imgUrl:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: img_url
    manyToOne:
        categorie:
            targetEntity: Categorie
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categorie_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
